config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :articles, only: :index
  resources :likes, only: %i[create destroy]

  root 'articles#index'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
# frozen_string_literal: true

class Article < ActiveResource::Base
  self.site = ENV.fetch('ARTICLE_API_URL').gsub(/(.+\/)(.+)\.json/, '\1')
  self.collection_name = ENV.fetch('ARTICLE_API_URL').gsub(/(.+\/)(.+)\.json/, '\2')

  def self.all_with_likes
    likes = Like.all.reduce({}) do |acc, like|
      acc[like.article_id] = like
      acc
    end

    all.each do |article|
      article.like = likes[article.id]
    end
  end

  def self.all_with_each_like
    all.each do |article|
      article.like = Like.find_by(article_id: article.id)
    end
  end

  def self.all_likes_by_ids
    articles = all

    ids = articles.map { |article| article.id }

    likes = Like.where(article_id: ids).reduce({}) do |acc, like|
      acc[like.article_id] = like
      acc
    end

    articles.each do |article|
      article.like = likes[article.id]
    end
  end

  def thumbnail_url
    self.photos.first.files.medium
  end

  def username
    self.user.first_name
  end

  def user_avatar
    self.user.current_avatar.small
  end
end

app/models/like.rb
# frozen_string_literal: true

class Like < ApplicationRecord
  belongs_to :article

  def article
    Article.all.find { |a| a.id == article_id }
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
# frozen_string_literal: true

class ArticlesController < ApplicationController
  def index; end

  private
    def articles
      @articles ||= Article.all_with_likes

      case params[:sort]
      when 'title'
        @articles.sort { |a, b| a.title <=> b.title }
      when 'closest'
        @articles.sort { |a, b| a.location.distance <=> b.location.distance }
      when 'popular'
        @articles.sort { |a, b| a.reactions.views <=> b.reactions.views }
      else
        @articles
      end
    end

    helper_method :articles
end

app/controllers/likes_controller.rb
# frozen_string_literal: true

class LikesController < ApplicationController
  def create
    article = Article.all.find { |a| a.id == params[:article_id].to_i }

    raise ActiveRecord::RecordNotFound unless article

    Like.create(article_id: article.id)

    redirect_to root_path
  end

  def destroy
    Like.find(params[:id]).destroy

    redirect_to root_path
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/articles/index.html.erb
<% content_for :header_title do %>
  Items offered
<% end %>

<% if articles.size.positive? %>
  <div class="articles__sorting">
    Sort by:
    <ul class="articles__sort-options">
      <li>
        <%= link_to 'Default', root_path, class: 'link' %>
      </li>
      <li>
        <%= link_to 'Title', root_path(params: { sort: 'title' }), class: 'link' %>
      </li>
      <li>
        <%= link_to 'Distance (closest first)', root_path(params: { sort: 'closest' }), class: 'link' %>
      </li>
      <li>
        <%= link_to 'Most popular', root_path(params: { sort: 'popular' }), class: 'link' %>
      </li>
    </ul>

  </div>
  <ul class="articles__list">
    <% articles.each do |article| %>
      <li class="article">
        <%= image_tag article.thumbnail_url, alt: '', class: 'article__thumbnail' %>
        <div class="article__info">
          <h2 class="article__title"><%= article.title %></h2>
          <p class="article__user">Listed by: <%= article.username %> <%= image_tag article.user_avatar, alt: '', class: 'article__user-avatar' %></p>
          <p>Distance <%= article.location.distance %></p>
          <p>Views <%= article.reactions.views %></p>
          <% if article.like %>
            <%= button_to("Unlike", like_path(article.like), method: :delete, class: "button button--liked") %>
          <% else %>
            <%= button_to("Like", likes_path(article_id: article.id), method: :post, class: "button") %>
          <% end %>
        </div>
      </li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Umuo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="app">
    <header class="header">
      <h1 class="header__title"><%= yield :header_title%></h1>
      <span class="header__logo">umou</span>
    </header>
    <main class="main">
      <%= yield %>
    </main>
  </body>
</html>